# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OpenGL_2D_ui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(992, 598)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 961, 571))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setMouseTracking(False)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(700, 480, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalSlider_rotate = QtWidgets.QSlider(self.groupBox_3)
        self.horizontalSlider_rotate.setGeometry(QtCore.QRect(760, 480, 181, 22))
        self.horizontalSlider_rotate.setMinimum(-100)
        self.horizontalSlider_rotate.setMaximum(100)
        self.horizontalSlider_rotate.setProperty("value", 0)
        self.horizontalSlider_rotate.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_rotate.setObjectName("horizontalSlider_rotate")
        self.checkBox_Dragging = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_Dragging.setEnabled(True)
        self.checkBox_Dragging.setGeometry(QtCore.QRect(220, 480, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_Dragging.setFont(font)
        self.checkBox_Dragging.setChecked(False)
        self.checkBox_Dragging.setObjectName("checkBox_Dragging")
        self.horizontalSlider_zoom = QtWidgets.QSlider(self.groupBox_3)
        self.horizontalSlider_zoom.setGeometry(QtCore.QRect(470, 480, 181, 22))
        self.horizontalSlider_zoom.setMaximum(200)
        self.horizontalSlider_zoom.setProperty("value", 150)
        self.horizontalSlider_zoom.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_zoom.setObjectName("horizontalSlider_zoom")
        self.label_20 = QtWidgets.QLabel(self.groupBox_3)
        self.label_20.setGeometry(QtCore.QRect(420, 480, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.pushButton_Exit = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_Exit.setGeometry(QtCore.QRect(810, 530, 112, 34))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_Exit.setFont(font)
        self.pushButton_Exit.setObjectName("pushButton_Exit")
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.groupBox_3)
        self.openGLWidget.setGeometry(QtCore.QRect(10, 20, 941, 431))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openGLWidget.sizePolicy().hasHeightForWidth())
        self.openGLWidget.setSizePolicy(sizePolicy)
        self.openGLWidget.setMouseTracking(False)
        self.openGLWidget.setObjectName("openGLWidget")
        self.pushButton_Animate = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_Animate.setGeometry(QtCore.QRect(250, 530, 112, 34))
        self.pushButton_Animate.setObjectName("pushButton_Animate")
        self.MouseLocation = QtWidgets.QLineEdit(self.groupBox_3)
        self.MouseLocation.setGeometry(QtCore.QRect(20, 480, 161, 22))
        self.MouseLocation.setText("")
        self.MouseLocation.setAlignment(QtCore.Qt.AlignCenter)
        self.MouseLocation.setObjectName("MouseLocation")
        self.pushButton_StopAnimation = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_StopAnimation.setGeometry(QtCore.QRect(400, 530, 161, 34))
        self.pushButton_StopAnimation.setObjectName("pushButton_StopAnimation")
        self.pushButton_ResumeAnimation = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_ResumeAnimation.setGeometry(QtCore.QRect(590, 530, 161, 34))
        self.pushButton_ResumeAnimation.setObjectName("pushButton_ResumeAnimation")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "OpenGL"))
        self.groupBox_3.setTitle(_translate("Dialog", "OpenGL Simple 2D Drawing"))
        self.label_2.setText(_translate("Dialog", "Rotate"))
        self.checkBox_Dragging.setText(_translate("Dialog", "Dragging"))
        self.label_20.setText(_translate("Dialog", "Zoom"))
        self.pushButton_Exit.setText(_translate("Dialog", "Exit"))
        self.pushButton_Animate.setText(_translate("Dialog", "Animate"))
        self.pushButton_StopAnimation.setText(_translate("Dialog", "Stop Animation"))
        self.pushButton_ResumeAnimation.setText(_translate("Dialog", "Resume Animation"))
